lib/finecode_web/router.ex
defmodule FinecodeWeb.Router do
  use FinecodeWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", FinecodeWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/about", PageController, :about
    get "/blog/", BlogController, :index
    get "/blog/:id", BlogController, :show
    get "/feeds/atom.xml", FeedController, :atom
  end

  # Other scopes may use custom stacks.
  # scope "/api", FinecodeWeb do
  #   pipe_through :api
  # end
end

lib/finecode_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= assigns[:page_title] || "FineCode - Exploring better coding" %></title>
    <link rel="icon" href="<%= Routes.static_path(@conn, "/images/favicon.png") %>" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/milligram/1.3.0/milligram.css">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/assets/app.css") %>"/>
    <link rel="alternate" href="<%= Routes.feed_url(@conn, :atom) %>" type="application/atom+xml" title="FineCode Atom Feed">
    <%= csrf_meta_tag() %>
  </head>
  <body>
    <header class="page-header wrapper">
      <a href="/">
        <img src="<%= Routes.static_path(@conn, "/images/logo.png") %>" alt="FineCode Logo" class="logo"/>
      </a>
      <nav role="navigation">
        <ul class="main-nav">
          <li><a href="<%= Routes.blog_path(@conn, :index) %>">Blog</a></li>
          <li><a href="<%= Routes.page_path(@conn, :about) %>">About</a></li>
        </ul>
      </nav>
    </header>
    <main role="main" class="wrapper">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/assets/app.js") %>"></script>
  </body>
</html>